name: Selenium Test Runs

on:
    workflow_dispatch:
    workflow_call:
    
    jobs:
        Run:
        runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        
        # Install .net core
        - name: Install .net core
        - uses: actions/setup-dotnet@v3
						with:
						dotnet-version: 6.0.x
						
				- name: Install Chrome
             run: |
            chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh
                        
        # Execute all unit tests in the solution
                - name: Run the test
          run: dotnet test UITestAutomation.csproj --configuration Release --no-build -- verbosity normal
