name: SeleniumTestRun

on:
		workflow_call:
		
	jobs:
		Run:
	runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v3
    
    - name: Install .net core
			uses: actions/setup-dotnet@v3
			with:
				dotnet-version: 6.0.x

      name: Install Google Chrome 

      run: |

              chmod +x ./scripts/InstallChrome.sh

                          ./scripts/InstallChrome.sh 

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test UITestAutomation.csproj --configuration Release --no-build -- verbosity normal
