name: Selenium Test Run

on:
    workflow_dispatch:
    workflow_call:
    
jobs:
    Run:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        
        # Install .NET core
        - name: Install .net core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x
            
        #- name: Instal Chrome
        - uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: stable
          
        - run: chrome --version
        
        - name: Restore
          run: dotnet restore UITestAutomation/UITestAutomation.csproj
          
        - name: Build
          run: dotnet build UITestAutomation/UITestAutomation.csproj --configuration Release --no-restore
          
        - name: Test run
          run: dotnet test UITestAutomation/UITestAutomation.csproj --configuration Release --no-build --logger "trx;logfilename=testResults.trx"

        - name: Test Report
          uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: Test Results            # Name of the check run which will be created
            path: UITestAutomation/TestResults/*.trx    # Path to test results
            reporter: dotnet-trx        # Format of test results
