name: Selenium Test Run
on:
	wokflow_dispatch:
	workflow_call:

	jobs:
		Test_Run:
			runs-on: ubuntu-latest
		
			steps:
			- uses: actions/checkout@v3

			- name: Run
			  run: dotnet test UITestAutomation.csproj --configuration Release --no-build -- verbosity normal
